// ============================================================
//  i18n dos exercícios — estrutura escalável (PT / EN / ES)
//  Chave = nome em inglês (como vem do banco / biblioteca).
//  Cada idioma: { name, exec[], tips[], errors[] }
//  Idioma padrão do app: PT. Fallback automático -> instruções
//  originais em inglês quando não houver tradução.
// ============================================================

// Idioma do usuário (localização do navegador). PT é o padrão.
export function detectLang() {
  try {
    const l = (navigator.language || 'pt').toLowerCase();
    if (l.startsWith('es')) return 'es';
    if (l.startsWith('en')) return 'en';
    return 'pt';
  } catch { return 'pt'; }
}

// Traduções em Português (linguagem simples e clara)
const PT = {
  // ---------- PEITO ----------
  'Barbell Bench Press - Medium Grip': { name: 'Supino Reto com Barra', exec: ['Deite no banco reto com os pés firmes no chão', 'Segure a barra um pouco mais aberto que os ombros', 'Desça a barra até encostar de leve no peito', 'Empurre para cima até esticar os braços'], tips: ['Mantenha as escápulas apoiadas no banco', 'Controle a descida'], errors: ['Quicar a barra no peito', 'Tirar o quadril do banco'] },
  'Barbell Incline Bench Press - Medium Grip': { name: 'Supino Inclinado com Barra', exec: ['Ajuste o banco inclinado (cerca de 30 a 45°)', 'Segure a barra na largura dos ombros', 'Desça a barra até a parte alta do peito', 'Empurre para cima controlando o movimento'], tips: ['Foque na parte superior do peito', 'Não deixe os cotovelos abrirem demais'], errors: ['Inclinar o banco em excesso', 'Descer a barra rápido demais'] },
  'Dumbbell Bench Press': { name: 'Supino Reto com Halteres', exec: ['Deite no banco com um halter em cada mão', 'Posicione os halteres na altura do peito', 'Empurre os halteres para cima até esticar os braços', 'Desça lentamente controlando'], tips: ['Mantenha os punhos firmes', 'Contraia o peito no topo'], errors: ['Bater os halteres um no outro com força', 'Descer sem controle'] },
  'Incline Dumbbell Press': { name: 'Supino Inclinado com Halteres', exec: ['Deite em um banco inclinado segurando um halter em cada mão', 'Posicione os halteres na altura do peito', 'Empurre os halteres para cima até estender os braços', 'Desça lentamente controlando o movimento'], tips: ['Mantenha os pés firmes no chão', 'Contraia o peito durante o movimento'], errors: ['Descer rápido demais', 'Arquear demais a lombar'] },
  'Cable Crossover': { name: 'Crossover na Polia', exec: ['Fique em pé entre as duas polias altas', 'Segure as alças com os braços abertos', 'Puxe as mãos para frente e para baixo até se cruzarem', 'Volte devagar abrindo os braços'], tips: ['Dê um leve passo à frente', 'Aperte o peito ao fechar'], errors: ['Usar muito os braços em vez do peito', 'Voltar o movimento sem controle'] },
  'Butterfly': { name: 'Voador (Peck Deck)', exec: ['Sente na máquina com as costas apoiadas', 'Segure as alças com os cotovelos levemente flexionados', 'Junte os braços à frente apertando o peito', 'Volte devagar abrindo até sentir o alongamento'], tips: ['Movimento só nos ombros, braços fixos', 'Aperte o peito no fechamento'], errors: ['Abrir demais e forçar o ombro', 'Soltar o peso de volta rápido'] },
  'Dips - Chest Version': { name: 'Mergulho nas Paralelas (foco peito)', exec: ['Apoie-se nas barras paralelas com os braços esticados', 'Incline o tronco levemente para frente', 'Desça flexionando os cotovelos até sentir o peito', 'Empurre para cima até esticar os braços'], tips: ['Tronco inclinado ativa mais o peito', 'Desça de forma controlada'], errors: ['Descer fundo demais e forçar o ombro', 'Balançar o corpo'] },
  'Pushups': { name: 'Flexão de Braço', exec: ['Apoie as mãos no chão na largura dos ombros', 'Mantenha o corpo reto da cabeça aos pés', 'Desça o peito em direção ao chão', 'Empurre de volta até esticar os braços'], tips: ['Contraia o abdômen o tempo todo', 'Cotovelos levemente para trás'], errors: ['Deixar o quadril cair', 'Não descer o suficiente'] },
  'Bent-Arm Dumbbell Pullover': { name: 'Pullover com Halter', exec: ['Deite no banco segurando um halter com as duas mãos', 'Leve o halter acima e atrás da cabeça', 'Sinta o alongamento do peito e dorsal', 'Traga de volta acima do peito'], tips: ['Movimento amplo e controlado', 'Mantenha leve flexão nos cotovelos'], errors: ['Usar carga pesada demais', 'Arquear muito as costas'] },
  'Around The Worlds': { name: 'Círculos com Halteres (Around the World)', exec: ['Deite no banco com um halter em cada mão ao lado do corpo', 'Faça um movimento circular amplo levando os halteres acima da cabeça', 'Retorne pelo mesmo caminho controlando', 'Mantenha leve flexão nos cotovelos'], tips: ['Use carga leve', 'Movimento lento e controlado'], errors: ['Carga pesada demais', 'Perder o controle do movimento'] },

  // ---------- COSTAS ----------
  'Pullups': { name: 'Barra Fixa (Pegada Pronada)', exec: ['Segure a barra com as palmas para frente, mãos abertas', 'Pendure com os braços esticados', 'Puxe o corpo até o queixo passar a barra', 'Desça devagar até esticar os braços'], tips: ['Puxe com as costas, não só com os braços', 'Controle a descida'], errors: ['Balançar o corpo (impulso)', 'Não esticar os braços embaixo'] },
  'Wide-Grip Lat Pulldown': { name: 'Puxada Aberta na Polia', exec: ['Sente na máquina e segure a barra bem aberto', 'Puxe a barra até a parte alta do peito', 'Aperte as costas no fim do movimento', 'Volte devagar até esticar os braços'], tips: ['Peito aberto e olhar à frente', 'Leve os cotovelos para baixo'], errors: ['Puxar atrás da nuca', 'Usar impulso do tronco'] },
  'Chin-Up': { name: 'Barra Fixa (Pegada Supinada)', exec: ['Segure a barra com as palmas viradas para você', 'Pendure com os braços esticados', 'Puxe até o queixo passar a barra', 'Desça controlando'], tips: ['Ativa bíceps e costas juntos', 'Mantenha o abdômen firme'], errors: ['Usar impulso das pernas', 'Subir só metade'] },
  'Bent Over Barbell Row': { name: 'Remada Curvada com Barra', exec: ['Incline o tronco à frente com os joelhos semiflexionados', 'Segure a barra na largura dos ombros', 'Puxe a barra em direção ao umbigo', 'Desça controlando até esticar os braços'], tips: ['Mantenha as costas retas', 'Aperte as escápulas no topo'], errors: ['Arredondar a coluna', 'Levantar o tronco ao puxar'] },
  'Seated Cable Rows': { name: 'Remada Sentada na Polia', exec: ['Sente com os pés apoiados e segure a alça', 'Mantenha as costas retas e o peito aberto', 'Puxe a alça em direção ao abdômen', 'Volte devagar esticando os braços'], tips: ['Aperte as escápulas ao puxar', 'Não jogue o tronco para trás'], errors: ['Curvar as costas', 'Usar impulso do corpo'] },
  'One-Arm Dumbbell Row': { name: 'Remada Unilateral com Halter (Serrote)', exec: ['Apoie um joelho e a mão no banco', 'Segure o halter com o outro braço esticado', 'Puxe o halter em direção ao quadril', 'Desça controlando'], tips: ['Mantenha as costas retas', 'Puxe com o cotovelo, não com a mão'], errors: ['Girar o tronco', 'Encolher o ombro'] },
  'Lying T-Bar Row': { name: 'Remada Cavalinho Apoiada', exec: ['Deite de bruços no banco inclinado da máquina', 'Segure a barra abaixo do peito', 'Puxe a barra em direção ao corpo', 'Desça controlando até esticar os braços'], tips: ['Aperte as costas no topo', 'Peito apoiado evita usar impulso'], errors: ['Tirar o peito do apoio', 'Descer rápido demais'] },
  'Barbell Deadlift': { name: 'Levantamento Terra com Barra', exec: ['Fique em pé com a barra sobre o meio do pé', 'Segure a barra com as costas retas e quadril abaixado', 'Levante empurrando o chão e estendendo o quadril', 'Desça controlando mantendo a coluna reta'], tips: ['Barra colada nas pernas', 'Suba peito e quadril juntos'], errors: ['Arredondar a coluna', 'Iniciar o movimento com as costas'] },
  'Hyperextensions (Back Extensions)': { name: 'Extensão Lombar (Hiperextensão)', exec: ['Posicione-se na cadeira romana com o quadril apoiado', 'Cruze os braços ou ponha as mãos na cabeça', 'Desça o tronco flexionando o quadril', 'Suba até alinhar o corpo'], tips: ['Não force além da linha do corpo', 'Movimento controlado'], errors: ['Hiperestender a lombar no topo', 'Usar impulso'] },
  'Bent-Arm Barbell Pullover': { name: 'Pullover com Barra', exec: ['Deite no banco segurando a barra acima do peito', 'Leve a barra atrás da cabeça flexionando os cotovelos', 'Sinta o alongamento', 'Traga de volta acima do peito'], tips: ['Use carga moderada', 'Controle todo o trajeto'], errors: ['Arquear demais as costas', 'Carga pesada demais'] },

  // ---------- OMBROS ----------
  'Barbell Shoulder Press': { name: 'Desenvolvimento com Barra', exec: ['Sente ou fique em pé com a barra na altura dos ombros', 'Segure um pouco mais aberto que os ombros', 'Empurre a barra acima da cabeça até esticar os braços', 'Desça controlando até os ombros'], tips: ['Mantenha o abdômen firme', 'Não arqueie a lombar'], errors: ['Empurrar o quadril para frente', 'Descer pouco'] },
  'Dumbbell Shoulder Press': { name: 'Desenvolvimento com Halteres', exec: ['Sente com as costas apoiadas e um halter em cada mão', 'Posicione os halteres na altura das orelhas', 'Empurre para cima até quase esticar os braços', 'Desça controlando'], tips: ['Punhos firmes e alinhados', 'Não trave os cotovelos com força'], errors: ['Bater os halteres no topo', 'Descer rápido demais'] },
  'Arnold Dumbbell Press': { name: 'Desenvolvimento Arnold', exec: ['Sente segurando os halteres à frente, palmas para você', 'Empurre girando os punhos para fora', 'Termine com os braços estendidos acima', 'Volte girando até a posição inicial'], tips: ['Movimento fluido e controlado', 'Use carga moderada'], errors: ['Girar rápido demais', 'Arquear as costas'] },
  'Side Lateral Raise': { name: 'Elevação Lateral', exec: ['Fique em pé com um halter em cada mão ao lado do corpo', 'Eleve os braços para os lados até a altura dos ombros', 'Mantenha leve flexão nos cotovelos', 'Desça devagar'], tips: ['Lidere com os cotovelos', 'Use carga leve e controlada'], errors: ['Usar impulso do corpo', 'Subir acima dos ombros'] },
  'Front Dumbbell Raise': { name: 'Elevação Frontal', exec: ['Fique em pé com os halteres à frente das coxas', 'Eleve um ou os dois braços à frente até a altura dos ombros', 'Mantenha leve flexão no cotovelo', 'Desça controlando'], tips: ['Não balance o tronco', 'Movimento lento'], errors: ['Usar impulso', 'Subir alto demais'] },
  'Standing Dumbbell Press': { name: 'Desenvolvimento em Pé com Halteres', exec: ['Fique em pé com os halteres na altura dos ombros', 'Mantenha o abdômen firme', 'Empurre para cima até esticar os braços', 'Desça controlando'], tips: ['Não arqueie a lombar', 'Pés afastados para estabilidade'], errors: ['Jogar o quadril à frente', 'Descer pouco'] },
  'Upright Barbell Row': { name: 'Remada Alta com Barra', exec: ['Segure a barra à frente do corpo com pegada fechada', 'Puxe a barra para cima rente ao corpo', 'Eleve até a altura do peito com os cotovelos altos', 'Desça controlando'], tips: ['Cotovelos sempre acima das mãos', 'Use carga moderada'], errors: ['Subir alto demais e forçar o ombro', 'Usar impulso'] },
  'Face Pull': { name: 'Face Pull na Polia', exec: ['Ajuste a polia na altura do rosto com corda', 'Puxe a corda em direção ao rosto, abrindo as mãos', 'Aperte a parte de trás dos ombros', 'Volte devagar'], tips: ['Ótimo para postura e ombro', 'Cotovelos altos'], errors: ['Usar carga pesada demais', 'Puxar com o tronco'] },
  'Barbell Rear Delt Row': { name: 'Remada para Posterior de Ombro', exec: ['Incline o tronco à frente segurando a barra', 'Puxe a barra em direção ao peito com cotovelos abertos', 'Aperte a parte de trás dos ombros', 'Desça controlando'], tips: ['Cotovelos abertos focam o posterior', 'Carga leve a moderada'], errors: ['Arredondar as costas', 'Usar impulso'] },

  // ---------- BÍCEPS ----------
  'Barbell Curl': { name: 'Rosca Direta com Barra', exec: ['Fique em pé segurando a barra com as palmas para cima', 'Mantenha os cotovelos junto ao corpo', 'Flexione os braços levando a barra ao peito', 'Desça controlando até esticar'], tips: ['Cotovelos parados', 'Aperte o bíceps no topo'], errors: ['Balançar o corpo', 'Usar impulso para subir'] },
  'Dumbbell Bicep Curl': { name: 'Rosca Direta com Halteres', exec: ['Fique em pé com um halter em cada mão, palmas para frente', 'Flexione os braços levando os halteres aos ombros', 'Aperte o bíceps no topo', 'Desça controlando'], tips: ['Pode alternar os braços', 'Cotovelos fixos'], errors: ['Balançar o tronco', 'Descer rápido demais'] },
  'Hammer Curls': { name: 'Rosca Martelo', exec: ['Segure os halteres com as palmas viradas para dentro', 'Mantenha os cotovelos junto ao corpo', 'Flexione levando os halteres aos ombros', 'Desça controlando'], tips: ['Trabalha bíceps e antebraço', 'Punhos firmes'], errors: ['Usar impulso', 'Abrir os cotovelos'] },
  'Preacher Curl': { name: 'Rosca Scott (no Banco)', exec: ['Apoie os braços no banco Scott segurando a barra', 'Flexione os braços levando a barra ao topo', 'Aperte o bíceps', 'Desça controlando sem esticar de forma brusca'], tips: ['Apoio elimina o impulso', 'Não estenda com tranco'], errors: ['Soltar o peso embaixo', 'Tirar os braços do apoio'] },
  'Concentration Curls': { name: 'Rosca Concentrada', exec: ['Sente e apoie o cotovelo na parte interna da coxa', 'Segure o halter com o braço estendido', 'Flexione concentrando no bíceps', 'Desça controlando'], tips: ['Isola muito bem o bíceps', 'Movimento lento'], errors: ['Mexer o ombro', 'Usar impulso'] },
  'Alternate Incline Dumbbell Curl': { name: 'Rosca Alternada no Banco Inclinado', exec: ['Deite no banco inclinado com os braços pendurados', 'Flexione um braço de cada vez levando o halter ao ombro', 'Aperte o bíceps no topo', 'Desça controlando e alterne'], tips: ['Alongamento maior do bíceps', 'Cotovelos parados'], errors: ['Balançar os braços', 'Subir os ombros'] },
  'Barbell Curls Lying Against An Incline': { name: 'Rosca com Barra Deitado no Inclinado', exec: ['Deite de bruços no banco inclinado segurando a barra', 'Deixe os braços pendurados estendidos', 'Flexione levando a barra para cima', 'Desça controlando'], tips: ['Apoio evita impulso', 'Foco total no bíceps'], errors: ['Tirar o peito do apoio', 'Soltar o peso'] },

  // ---------- TRÍCEPS ----------
  'Triceps Pushdown': { name: 'Tríceps na Polia (Barra)', exec: ['Fique em pé de frente para a polia alta segurando a barra', 'Mantenha os cotovelos junto ao corpo', 'Empurre a barra para baixo até esticar os braços', 'Volte controlando'], tips: ['Cotovelos fixos ao lado do corpo', 'Aperte o tríceps embaixo'], errors: ['Abrir os cotovelos', 'Usar o tronco para empurrar'] },
  'Triceps Pushdown - Rope Attachment': { name: 'Tríceps na Polia com Corda', exec: ['Segure a corda na polia alta com as palmas viradas', 'Mantenha os cotovelos junto ao corpo', 'Empurre para baixo abrindo a corda no final', 'Volte controlando'], tips: ['Abra a corda no fim para mais contração', 'Cotovelos parados'], errors: ['Mexer os ombros', 'Usar impulso'] },
  'Lying Triceps Press': { name: 'Tríceps Testa Deitado', exec: ['Deite no banco segurando a barra acima da testa', 'Mantenha os cotovelos apontados para cima', 'Flexione levando a barra perto da testa', 'Estenda os braços de volta'], tips: ['Só os antebraços se movem', 'Controle a descida'], errors: ['Abrir os cotovelos', 'Descer rápido demais'] },
  'Dips - Triceps Version': { name: 'Mergulho nas Paralelas (foco tríceps)', exec: ['Apoie-se nas paralelas com o tronco ereto', 'Mantenha os cotovelos próximos ao corpo', 'Desça flexionando os braços', 'Empurre para cima até esticar'], tips: ['Tronco reto foca o tríceps', 'Desça controlando'], errors: ['Inclinar muito à frente', 'Descer fundo demais'] },
  'Standing Dumbbell Triceps Extension': { name: 'Tríceps Francês em Pé', exec: ['Segure um halter com as duas mãos acima da cabeça', 'Mantenha os cotovelos apontados para cima', 'Desça o halter atrás da cabeça flexionando', 'Estenda os braços de volta'], tips: ['Cotovelos parados e próximos', 'Movimento controlado'], errors: ['Abrir os cotovelos', 'Arquear as costas'] },
  'Tricep Dumbbell Kickback': { name: 'Tríceps Coice com Halter', exec: ['Incline o tronco à frente com o braço junto ao corpo', 'Cotovelo flexionado a 90°', 'Estenda o braço para trás até esticar', 'Volte controlando'], tips: ['Cotovelo parado e alto', 'Aperte o tríceps no fim'], errors: ['Balançar o braço', 'Mover o cotovelo'] },
  'Close-Grip Barbell Bench Press': { name: 'Supino Fechado (foco tríceps)', exec: ['Deite no banco e segure a barra com as mãos próximas', 'Desça a barra até a parte baixa do peito', 'Mantenha os cotovelos junto ao corpo', 'Empurre para cima até esticar'], tips: ['Pegada na largura dos ombros', 'Cotovelos não abrem'], errors: ['Pegada estreita demais', 'Abrir os cotovelos'] },

  // ---------- ANTEBRAÇO ----------
  'Palms-Up Barbell Wrist Curl Over A Bench': { name: 'Rosca de Punho (Palmas para Cima)', exec: ['Apoie os antebraços no banco com as palmas para cima', 'Deixe os punhos para fora da borda segurando a barra', 'Flexione os punhos para cima', 'Desça controlando'], tips: ['Movimento só nos punhos', 'Use carga leve'], errors: ['Mexer os antebraços', 'Amplitude curta'] },
  'Palms-Down Wrist Curl Over A Bench': { name: 'Rosca de Punho Invertida (Palmas para Baixo)', exec: ['Apoie os antebraços no banco com as palmas para baixo', 'Deixe os punhos para fora da borda segurando a barra', 'Estenda os punhos para cima', 'Desça controlando'], tips: ['Trabalha a parte de cima do antebraço', 'Carga leve'], errors: ['Usar impulso', 'Mover os antebraços'] },
  'Wrist Roller': { name: 'Enrolador de Punho', exec: ['Segure o rolo com os braços estendidos à frente', 'Gire os punhos enrolando a corda e subindo o peso', 'Continue até o peso chegar ao topo', 'Desenrole controlando'], tips: ['Braços parados à frente', 'Controle na descida'], errors: ['Abaixar os braços', 'Soltar o peso rápido'] },

  // ---------- PERNAS (QUADRÍCEPS) ----------
  'Barbell Squat': { name: 'Agachamento Livre com Barra', exec: ['Apoie a barra na parte alta das costas', 'Pés na largura dos ombros, pontas levemente para fora', 'Agache flexionando joelhos e quadril até as coxas paralelas', 'Suba empurrando o chão até esticar'], tips: ['Joelhos na direção dos pés', 'Peito aberto e coluna reta'], errors: ['Juntar os joelhos', 'Arredondar a lombar'] },
  'Front Barbell Squat': { name: 'Agachamento Frontal', exec: ['Apoie a barra à frente, sobre os ombros', 'Mantenha os cotovelos altos e o tronco ereto', 'Agache até as coxas ficarem paralelas', 'Suba controlando'], tips: ['Tronco bem ereto', 'Cotovelos sempre altos'], errors: ['Inclinar o tronco à frente', 'Deixar os cotovelos caírem'] },
  'Leg Press': { name: 'Leg Press', exec: ['Sente na máquina com os pés na plataforma', 'Solte a trava e desça flexionando os joelhos', 'Desça até cerca de 90° sem soltar a lombar', 'Empurre de volta sem travar os joelhos'], tips: ['Pés na largura dos ombros', 'Não estenda com tranco'], errors: ['Descer demais e soltar o quadril', 'Travar os joelhos no topo'] },
  'Leg Extensions': { name: 'Cadeira Extensora', exec: ['Sente na máquina com os tornozelos atrás do rolo', 'Estenda as pernas para cima até esticar', 'Aperte o quadríceps no topo', 'Desça controlando'], tips: ['Movimento lento e controlado', 'Não trave o joelho com força'], errors: ['Usar impulso', 'Descer rápido demais'] },
  'Hack Squat': { name: 'Agachamento Hack (Máquina)', exec: ['Apoie as costas e ombros na máquina', 'Pés na plataforma, na largura dos ombros', 'Agache flexionando os joelhos', 'Suba empurrando sem travar os joelhos'], tips: ['Costas sempre apoiadas', 'Joelhos na direção dos pés'], errors: ['Tirar as costas do apoio', 'Descer com impulso'] },
  'Goblet Squat': { name: 'Agachamento Goblet (com Halter)', exec: ['Segure um halter junto ao peito com as duas mãos', 'Pés na largura dos ombros', 'Agache mantendo o tronco ereto', 'Suba empurrando o chão'], tips: ['Cotovelos por dentro dos joelhos', 'Peito aberto'], errors: ['Inclinar o tronco à frente', 'Calcanhares saindo do chão'] },
  'Dumbbell Lunges': { name: 'Afundo com Halteres', exec: ['Fique em pé com um halter em cada mão', 'Dê um passo à frente e desça o joelho de trás', 'Desça até formar 90° nas duas pernas', 'Empurre de volta à posição inicial'], tips: ['Tronco ereto', 'Joelho da frente alinhado com o pé'], errors: ['Joelho passando muito a ponta do pé', 'Desequilibrar o corpo'] },
  'Barbell Walking Lunge': { name: 'Afundo Caminhando com Barra', exec: ['Apoie a barra nas costas', 'Dê um passo à frente descendo o joelho de trás', 'Empurre e traga a perna de trás à frente', 'Continue alternando as pernas caminhando'], tips: ['Passos firmes e controlados', 'Olhar à frente'], errors: ['Tronco caindo à frente', 'Passos curtos demais'] },
  'Bodyweight Squat': { name: 'Agachamento Livre (Peso do Corpo)', exec: ['Fique em pé com os pés na largura dos ombros', 'Estenda os braços à frente para equilíbrio', 'Agache flexionando joelhos e quadril', 'Suba até esticar as pernas'], tips: ['Calcanhares sempre no chão', 'Coluna reta'], errors: ['Joelhos para dentro', 'Não descer o suficiente'] },
  'Barbell Step Ups': { name: 'Subida no Banco com Barra', exec: ['Apoie a barra nas costas em frente a um step/banco', 'Suba apoiando um pé por cima do banco', 'Estenda a perna subindo todo o corpo', 'Desça controlando e alterne'], tips: ['Empurre com o calcanhar do pé de cima', 'Tronco ereto'], errors: ['Impulsionar com a perna de baixo', 'Banco alto demais'] },

  // ---------- PERNAS (POSTERIOR / GLÚTEO) ----------
  'Lying Leg Curls': { name: 'Mesa Flexora (Deitado)', exec: ['Deite de bruços com os tornozelos sob o rolo', 'Segure os apoios laterais', 'Flexione os joelhos trazendo o rolo ao glúteo', 'Desça controlando'], tips: ['Quadril apoiado na maca', 'Movimento controlado'], errors: ['Levantar o quadril', 'Usar impulso'] },
  'Seated Leg Curl': { name: 'Cadeira Flexora (Sentado)', exec: ['Sente na máquina com as pernas sobre o rolo', 'Ajuste o apoio sobre as coxas', 'Flexione os joelhos puxando o rolo para baixo', 'Volte controlando'], tips: ['Costas apoiadas', 'Aperte o posterior no fim'], errors: ['Mexer o quadril', 'Soltar o peso rápido'] },
  'Romanian Deadlift': { name: 'Levantamento Terra Romeno', exec: ['Fique em pé segurando a barra à frente das coxas', 'Joelhos levemente flexionados e fixos', 'Desça a barra empurrando o quadril para trás', 'Suba estendendo o quadril'], tips: ['Barra rente às pernas', 'Sinta o alongamento posterior'], errors: ['Arredondar a coluna', 'Flexionar muito os joelhos'] },
  'Stiff-Legged Barbell Deadlift': { name: 'Stiff (Terra com Pernas Estendidas)', exec: ['Fique em pé com a barra à frente das coxas', 'Mantenha as pernas quase estendidas', 'Desça a barra empurrando o quadril para trás', 'Suba contraindo glúteo e posterior'], tips: ['Coluna sempre reta', 'Desça até sentir o alongamento'], errors: ['Curvar as costas', 'Descer com as costas em vez do quadril'] },
  'Good Morning': { name: 'Bom Dia (Good Morning)', exec: ['Apoie a barra na parte alta das costas', 'Joelhos levemente flexionados', 'Incline o tronco à frente empurrando o quadril para trás', 'Volte estendendo o quadril'], tips: ['Use carga leve', 'Coluna reta o tempo todo'], errors: ['Arredondar a lombar', 'Usar carga pesada demais'] },
  'Kettlebell One-Legged Deadlift': { name: 'Terra Unilateral com Kettlebell', exec: ['Segure o kettlebell em uma mão em pé', 'Apoie em uma perna e incline o tronco à frente', 'Estenda a perna livre para trás mantendo equilíbrio', 'Volte contraindo o glúteo'], tips: ['Movimento lento para equilíbrio', 'Coluna reta'], errors: ['Curvar as costas', 'Perder o equilíbrio'] },
  'Barbell Hip Thrust': { name: 'Elevação de Quadril com Barra (Hip Thrust)', exec: ['Apoie as costas em um banco e a barra sobre o quadril', 'Pés firmes no chão', 'Eleve o quadril contraindo o glúteo até o tronco alinhar', 'Desça controlando'], tips: ['Aperte o glúteo no topo', 'Queixo levemente para baixo'], errors: ['Hiperestender a lombar', 'Subir pouco o quadril'] },
  'Barbell Glute Bridge': { name: 'Ponte de Glúteo com Barra', exec: ['Deite no chão com a barra sobre o quadril', 'Pés apoiados perto do glúteo', 'Eleve o quadril contraindo o glúteo', 'Desça controlando'], tips: ['Aperte o glúteo no topo', 'Abdômen firme'], errors: ['Forçar a lombar', 'Empurrar com a ponta dos pés'] },
  'Glute Kickback': { name: 'Coice de Glúteo (Quatro Apoios)', exec: ['Fique em quatro apoios no chão ou na máquina', 'Mantenha o joelho flexionado', 'Empurre o pé para cima e para trás contraindo o glúteo', 'Volte controlando'], tips: ['Aperte o glúteo no topo', 'Não arqueie a lombar'], errors: ['Usar impulso', 'Forçar a coluna'] },
  'Hip Lift with Band': { name: 'Elevação de Quadril com Faixa', exec: ['Deite com a faixa sobre o quadril ou nos joelhos', 'Pés apoiados no chão', 'Eleve o quadril contra a resistência da faixa', 'Desça controlando'], tips: ['Aperte o glúteo no topo', 'Joelhos afastados contra a faixa'], errors: ['Subir com a lombar', 'Movimento rápido demais'] },
  'Step-up with Knee Raise': { name: 'Subida no Step com Elevação de Joelho', exec: ['Fique em frente a um step', 'Suba apoiando um pé sobre o step', 'No topo, eleve o joelho da outra perna', 'Desça controlando e alterne'], tips: ['Equilíbrio e controle', 'Empurre com o calcanhar'], errors: ['Impulsionar com a perna de baixo', 'Perder o equilíbrio'] },
  'Cable Hip Adduction': { name: 'Adução de Quadril na Polia', exec: ['Prenda a caneleira no tornozelo, lado para a polia', 'Puxe a perna em direção à linha do corpo cruzando à frente', 'Aperte a parte interna da coxa', 'Volte controlando'], tips: ['Tronco firme', 'Movimento controlado'], errors: ['Usar impulso', 'Girar o tronco'] },

  // ---------- PANTURRILHA ----------
  'Standing Calf Raises': { name: 'Panturrilha em Pé (Máquina)', exec: ['Fique em pé na máquina com a ponta dos pés na borda', 'Apoie os ombros sob os apoios', 'Eleve os calcanhares o máximo possível', 'Desça sentindo o alongamento'], tips: ['Amplitude total', 'Pausa de 1s no topo'], errors: ['Amplitude curta', 'Descer rápido demais'] },
  'Seated Calf Raise': { name: 'Panturrilha Sentado', exec: ['Sente na máquina com a ponta dos pés na borda', 'Apoie o peso sobre os joelhos', 'Eleve os calcanhares o máximo possível', 'Desça controlando'], tips: ['Foca o sóleo (panturrilha profunda)', 'Amplitude completa'], errors: ['Movimento curto', 'Não alongar embaixo'] },
  'Calf Press On The Leg Press Machine': { name: 'Panturrilha no Leg Press', exec: ['Sente no leg press com a ponta dos pés na borda da plataforma', 'Estenda as pernas (sem travar os joelhos)', 'Empurre a plataforma com a ponta dos pés', 'Volte sentindo o alongamento'], tips: ['Joelhos levemente flexionados', 'Amplitude total'], errors: ['Travar os joelhos', 'Amplitude curta'] },
  'Donkey Calf Raises': { name: 'Panturrilha Burrinho (Inclinado)', exec: ['Incline o tronco à frente com apoio nas mãos', 'Ponta dos pés numa elevação', 'Eleve os calcanhares contraindo a panturrilha', 'Desça alongando'], tips: ['Alongamento maior nessa posição', 'Movimento controlado'], errors: ['Dobrar muito os joelhos', 'Amplitude curta'] },

  // ---------- ABDÔMEN / CORE ----------
  'Crunches': { name: 'Abdominal Curto (Crunch)', exec: ['Deite com os joelhos flexionados e pés no chão', 'Mãos atrás da cabeça ou no peito', 'Eleve o tronco contraindo o abdômen', 'Desça controlando'], tips: ['Não puxe o pescoço', 'Expire ao subir'], errors: ['Puxar a cabeça com as mãos', 'Usar impulso'] },
  'Plank': { name: 'Prancha Abdominal', exec: ['Apoie os antebraços e as pontas dos pés no chão', 'Mantenha o corpo reto da cabeça aos pés', 'Contraia o abdômen e o glúteo', 'Segure a posição pelo tempo definido'], tips: ['Não deixe o quadril cair', 'Respire normalmente'], errors: ['Levantar o quadril', 'Deixar a lombar afundar'] },
  'Hanging Leg Raise': { name: 'Elevação de Pernas na Barra', exec: ['Pendure-se na barra com os braços estendidos', 'Mantenha o corpo estável', 'Eleve as pernas à frente até a altura do quadril', 'Desça controlando sem balançar'], tips: ['Controle a descida', 'Contraia o abdômen'], errors: ['Balançar o corpo', 'Usar impulso'] },
  'Cable Crunch': { name: 'Abdominal na Polia', exec: ['Ajoelhe de frente para a polia alta segurando a corda', 'Segure a corda perto da cabeça', 'Flexione o tronco contraindo o abdômen', 'Volte controlando'], tips: ['Movimento vem do abdômen, não dos braços', 'Quadril parado'], errors: ['Puxar com os braços', 'Mexer o quadril'] },
  'Russian Twist': { name: 'Rotação Russa (Russian Twist)', exec: ['Sente com os joelhos flexionados e tronco inclinado', 'Segure um peso com as duas mãos', 'Gire o tronco de um lado para o outro', 'Mantenha o abdômen contraído'], tips: ['Movimento vem do tronco', 'Pode tirar os pés do chão para dificultar'], errors: ['Girar só os braços', 'Curvar as costas'] },
  'Decline Crunch': { name: 'Abdominal no Banco Declinado', exec: ['Deite no banco declinado prendendo os pés', 'Mãos no peito ou atrás da cabeça', 'Eleve o tronco contraindo o abdômen', 'Desça controlando'], tips: ['Não puxe o pescoço', 'Controle a descida'], errors: ['Usar impulso', 'Puxar a cabeça'] },
  'Flat Bench Lying Leg Raise': { name: 'Elevação de Pernas Deitado no Banco', exec: ['Deite no banco segurando atrás da cabeça', 'Pernas estendidas', 'Eleve as pernas até ficarem na vertical', 'Desça controlando sem encostar no chão'], tips: ['Lombar apoiada no banco', 'Movimento controlado'], errors: ['Arquear a lombar', 'Descer rápido demais'] },
  'Oblique Crunches': { name: 'Abdominal Oblíquo', exec: ['Deite com os joelhos flexionados para um lado', 'Mãos atrás da cabeça', 'Eleve o tronco contraindo o oblíquo', 'Desça controlando e troque o lado'], tips: ['Foca a lateral do abdômen', 'Não puxe o pescoço'], errors: ['Usar impulso', 'Puxar a cabeça'] },
  'Air Bike': { name: 'Abdominal Bicicleta', exec: ['Deite com as mãos atrás da cabeça', 'Eleve as pernas e simule pedalar', 'Leve o cotovelo ao joelho oposto', 'Alterne os lados de forma controlada'], tips: ['Movimento lento e controlado', 'Gire o tronco, não só o cotovelo'], errors: ['Puxar o pescoço', 'Ir rápido demais sem contrair'] },
  'Standing Cable Wood Chop': { name: 'Rotação no Cabo (Wood Chop)', exec: ['Fique de lado para a polia segurando a alça com as duas mãos', 'Puxe diagonalmente de cima para baixo (ou ao contrário)', 'Gire o tronco acompanhando o movimento', 'Volte controlando'], tips: ['Força vem do core', 'Pés firmes'], errors: ['Usar só os braços', 'Perder a postura'] },

  // ---------- TRAPÉZIO ----------
  'Barbell Shrug': { name: 'Encolhimento com Barra', exec: ['Fique em pé segurando a barra à frente das coxas', 'Mantenha os braços estendidos', 'Eleve os ombros em direção às orelhas', 'Desça controlando'], tips: ['Movimento só nos ombros', 'Pausa no topo'], errors: ['Girar os ombros', 'Flexionar os braços'] },
  'Dumbbell Shrug': { name: 'Encolhimento com Halteres', exec: ['Fique em pé com um halter em cada mão ao lado do corpo', 'Braços estendidos', 'Eleve os ombros em direção às orelhas', 'Desça controlando'], tips: ['Aperte o trapézio no topo', 'Não use impulso'], errors: ['Rodar os ombros', 'Flexionar os cotovelos'] },
  'Cable Shrugs': { name: 'Encolhimento na Polia', exec: ['Fique de frente para a polia baixa segurando a barra', 'Braços estendidos', 'Eleve os ombros para cima', 'Desça controlando'], tips: ['Tensão constante do cabo', 'Pausa no topo'], errors: ['Usar impulso', 'Girar os ombros'] },
  'Barbell Shrug Behind The Back': { name: 'Encolhimento com Barra por Trás', exec: ['Segure a barra atrás do corpo com os braços estendidos', 'Eleve os ombros em direção às orelhas', 'Aperte o trapézio no topo', 'Desça controlando'], tips: ['Ativa o trapézio de forma diferente', 'Use carga moderada'], errors: ['Inclinar o tronco', 'Flexionar os braços'] },

  // ---------- CARDIO ----------
  'Mountain Climbers': { name: 'Escalador (Mountain Climber)', exec: ['Comece na posição de prancha alta', 'Traga um joelho em direção ao peito', 'Alterne as pernas rapidamente', 'Mantenha o abdômen contraído'], tips: ['Quadril estável', 'Ritmo constante'], errors: ['Levantar muito o quadril', 'Perder a postura'] },
  'Rope Jumping': { name: 'Pular Corda', exec: ['Segure a corda com as mãos ao lado do corpo', 'Gire a corda com os punhos', 'Salte com os dois pés a cada giro', 'Mantenha um ritmo constante'], tips: ['Saltos baixos e leves', 'Olhar à frente'], errors: ['Saltar alto demais', 'Usar muito os braços'] },
  'Running, Treadmill': { name: 'Corrida na Esteira', exec: ['Comece com uma caminhada para aquecer', 'Aumente a velocidade gradualmente até o ritmo de corrida', 'Mantenha a postura ereta e passada confortável', 'Reduza a velocidade no fim para desacelerar'], tips: ['Não se segure no painel ao correr', 'Hidrate-se'], errors: ['Começar rápido demais sem aquecer', 'Pisar muito à frente do corpo'] },
  'Bicycling': { name: 'Bicicleta (Ergométrica)', exec: ['Ajuste o banco na altura do quadril', 'Comece pedalando leve para aquecer', 'Aumente a resistência conforme o objetivo', 'Mantenha um ritmo constante'], tips: ['Joelhos alinhados ao pedalar', 'Postura ereta'], errors: ['Banco muito baixo (força o joelho)', 'Resistência alta demais no começo'] },
};

// Rótulos da interface por idioma
const LABELS = {
  pt: { exec: 'Execução', tips: 'Dicas', errors: 'Erros comuns' },
  en: { exec: 'How to', tips: 'Tips', errors: 'Common mistakes' },
  es: { exec: 'Ejecución', tips: 'Consejos', errors: 'Errores comunes' },
};

const DICT = { pt: PT, en: {}, es: {} };

// Retorna a tradução do exercício no idioma pedido (fallback: pt -> nada)
export function getExerciseI18n(name, lang = 'pt') {
  if (!name) return null;
  const key = String(name).trim();
  const table = DICT[lang] || DICT.pt;
  return table[key] || DICT.pt[key] || null;
}

export function i18nLabels(lang = 'pt') {
  return LABELS[lang] || LABELS.pt;
}

// Nome do exercício traduzido (fallback: nome original em inglês)
export function exerciseDisplayName(name, lang = 'pt') {
  const t = getExerciseI18n(name, lang);
  return t?.name || name;
}
